EP3/config/routes.rb
Rails.application.routes.draw do
  get 'controll_user/index'
  get 'controll_user/analise'

  resources :cardapio
  resources :routines
  resources :products
  resources :orders
  root 'main#index'

  get 'account_manager/index'
  get 'account_manager/emp_entry_time'
  get 'account_manager/emp_exit_time'
  get 'account_manager/emp_activity'
  get 'account_manager/atualiza'
    get 'account_manager/caixa'

  Rails.application.routes.draw do
    devise_for :users, :controllers => { :registrations => 'registrations'}
  end

end

EP3/app/models/routine.rb
class Routine < ActiveRecord::Base
end

EP3/app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /routines
  # GET /routines.json
  def index
    @routines = Routine.all
    @user_entered = Routine.where(["cpf = :u", { u: current_user.cpf }]).last

    if (@user_entered == nil)
      redirect_to action: "emp_entry_time", controller: "account_manager"
    else
      if (@user_entered != nil) && (@user_entered.status == nil)
        @user_entered.status = 0
      end
      @entered = @user_entered.status
    end
  end

  # GET /routines/1
  # GET /routines/1.json
  def show
  end

  # GET /routines/new
  def new
    @routine = Routine.new
  end

  # GET /routines/1/edit
  def edit
    @routine = Routine.find(current_routine.id)

  end

  # POST /routines
  # POST /routines.json
  def create
    @routine = Routine.new(routine_params)

    respond_to do |format|
      if @routine.save
        format.html { redirect_to @routine, notice: 'Rotina criada com sucesso!' }
        format.json { render :show, status: :created, location: @routine }
      else
        format.html { render :new }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routines/1
  # PATCH/PUT /routines/1.json
  def update
    respond_to do |format|
      if @routine.update(routine_params)
        format.html { redirect_to @routine, notice: 'Rotina atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @routine }
      else
        format.html { render :edit }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routines/1
  # DELETE /routines/1.json
  def destroy
    @routine.destroy
    respond_to do |format|
      format.html { redirect_to routines_url, notice: 'Rotina deletada com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = Routine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def routine_params
      params.require(:routine).permit(:name, :hour, :product)
    end
end

EP3/app/helpers/routines_helper.rb
module RoutinesHelper
end

EP3/app/views/routines/_form.html.erb
<%= form_for(@routine) do |f| %>
  <% if @routine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@routine.errors.count, "error") %> prohibited this routine from being saved:</h2>

      <ul>
      <% @routine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.time_select :hour %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

EP3/app/views/routines/edit.html.erb
<h1>Editar Rotinas</h1>

<%= render 'form' %>
<%if policy(@routine).edit? %>
  <%= link_to 'Mostrar', @routine %> |
  <%= link_to 'Voltar', routines_path %>
<%end%>

EP3/app/views/routines/index.html.erb
<%if policy(@routines).index? %>

  <%if @entered == 0 %>
    <%= button_to'Efetuar Entrada!', account_manager_emp_entry_time_path, class: "btn btn-primary",:method => :get  %><br>

  <%else%>
    <%= button_to 'Realizar Atividades', account_manager_emp_activity_path, class: "btn btn-primary",:method => :get  %><br>
    <%= button_to 'Efetuar Saída', account_manager_emp_exit_time_path, class: "btn btn-primary",:method => :get  %><br>
    <%end%>

    <%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>

<%else%>
  <% flash[:notice] = "Você não possui permissão para esta ação!" %>
<%end%>

EP3/app/views/routines/new.html.erb
<%if policy(@routine).new? %>
  <h1>Nova Rotina</h1>

  <%= render 'form' %>

  <%= link_to 'Voltar', routines_path %>
<%end%>

EP3/app/views/routines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @routine.name %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @routine.hour %>
</p>

<p>
  <strong>Product:</strong>
  <%= @routine.product %>
</p>

<%if policy(@routine).show? %>
<%= link_to 'Editar', edit_routine_path(@routine) %> |
<%= link_to 'Voltar', routines_path %>
<%end%>