EP3/config/routes.rb
Rails.application.routes.draw do
  get 'controll_user/index'
  get 'controll_user/analise'

  resources :cardapio
  resources :routines
  resources :products
  resources :orders
  root 'main#index'

  get 'account_manager/index'
  get 'account_manager/emp_entry_time'
  get 'account_manager/emp_exit_time'
  get 'account_manager/emp_activity'
  get 'account_manager/atualiza'
    get 'account_manager/caixa'

  Rails.application.routes.draw do
    devise_for :users, :controllers => { :registrations => 'registrations'}
  end

end

EP3/app/controllers/account_manager_controller.rb
class AccountManagerController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def emp_activity
    @orders = Order.all
    @routines = Routine.all
    authorize @orders
    authorize @routines
  end

  def emp_entry_time
    @routine = Routine.new
    @routine.name = current_user.name
    @routine.hourIn =Time.now
    @routine.cpf = current_user.cpf
    @routine.status = 1
    @routine.save
    authorize @routine
  end

  def emp_exit_time
    @routine = Routine.where(["cpf = :u", { u: current_user.cpf }]).last
    @routine.hourOut =Time.now
    @routine.status = 0
    @routine.save
    authorize @routine
  end

  def caixa
    @orders = Order.all
    @products = Product.all
    authorize @orders
    authorize @products
  end

end

EP3/app/helpers/account_manager_helper.rb
module AccountManagerHelper
end

EP3/app/views/account_manager/caixa.html.erb
<h1>Acompanhamento de Caixa</h1>
<%@caixa_total = 0.0%>

<h3>Todos pedidos realizados</h3>

<table width="40%" border ="1" >
 <thead>
 <tr lign="center">
    <th>Produto </th>
    <th>Quantidade</th>
    <th>Endereço</th>
    <th>Status </th>
 </tr>
 </thead>

 <tbody>
   <% @orders.each do |order| %>
    <% @products.each do |product| %>
      <%if (order.name == product.name) && (order.status == "Produto Entregue!")%>
        <%@caixa_total += product.price * order.amount%>
      <%end%>
      <%end%>

        <tr align="center">
            <td><%= order.name %></td>
            <td><%= order.amount %></td>
            <td><%= order.adress %></td>
            <td><%= order.status %></td>
        </tr>
      <%end%>

  </tbody>
</table>
<br>

<br>
<b>CAIXA TOTAL <%=@caixa_total%></b>
<br><br>

<%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>

EP3/app/views/account_manager/emp_activity.html.erb
<h1>Acompanhamento de Pedidos</h1>

<table width="100%" border ="1" cellpadding="4" >
 <thead>
 <tr align="center">
    <th>Num. Pedido</th>
    <th>Produto</th>
    <th>Quantidade</th>
    <th>Status </th>
    <th>Controle </th>
 </tr>
 </thead>

 <tbody>
   <%@orders.each do |order| %>
        <tr align="center">
            <td><%= order.id %></td>
            <td><%= order.name %></td>
            <td><%= order.amount %></td>
            <td><%= order.status %></td>

            <td>
            <%= form_for order do |f| %>
                <%= f.select :status, ['Produto em Preparo !', 'Produto Finalizado!', 'Produto Entregue!'] %>
            </td>

            <td><%= f.submit "OK"%><% end %></td>
              <td><%= link_to 'Cancelar', order, method: :delete, data: { confirm: 'Tem certeza?' ,} %></td>
            <%end%>
        </tr>

  </tbody>
</table>
<br>
<%= button_to 'Voltar', routines_path, class: "btn btn-primary",:method => :get  %>

EP3/app/views/account_manager/emp_entry_time.html.erb
<%flash[:notice] = "Entrada realizada com sucesso!"%>
<%= button_to 'OK!', routines_path, class: "btn btn-primary",:method => :get  %><br>

EP3/app/views/account_manager/emp_exit_time.html.erb
<% flash[:notice] = "Saída realizada com sucesso!" %>

<%= button_to 'OK!', account_manager_index_path, class: "btn btn-primary",:method => :get  %><br>

EP3/app/views/account_manager/index.html.erb
<h1>Sua conta</h1>

<%if current_user.normal_user?  || current_user.employee? || current_user.admin?%>
<p>O que deseja fazer?</p>
  <%= link_to 'Realizar um novo pedido?', new_order_path %><br>
  <%= link_to 'Verificar andamento do(s) seu(s) pedido(s)!', orders_path %><br>
  <%if current_user.employee? || current_user.admin?%>
    <%= link_to 'Realizar Procedimentos!', routines_path %><br><br>
      <%if current_user.admin?%>
        <%= link_to 'Visualizar Usuários!', controll_user_index_path %><br>
        <%= link_to 'Visualizar lista de Produtos!', products_path %><br>
        <%= link_to 'Cadastrar novos Produtos!', new_product_path %><br>
        <%= link_to 'Cadastrar novos Funcionários!', new_user_registration_path %><br>
        <%= link_to 'Visualizar Caixa!', account_manager_caixa_path %><br>
    <%end%>
  <%end%>
<%end%>