EP3/config/routes.rb
Rails.application.routes.draw do
  get 'controll_user/index'
  get 'controll_user/analise'

  resources :cardapio
  resources :routines
  resources :products
  resources :orders
  root 'main#index'

  get 'account_manager/index'
  get 'account_manager/emp_entry_time'
  get 'account_manager/emp_exit_time'
  get 'account_manager/emp_activity'
  get 'account_manager/atualiza'
    get 'account_manager/caixa'

  Rails.application.routes.draw do
    devise_for :users, :controllers => { :registrations => 'registrations'}
  end

end

EP3/app/models/order.rb
class Order < ActiveRecord::Base
end

EP3/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Pedido realizado com sucesso!' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to account_manager_emp_activity_path, notice: 'Pedido atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to account_manager_emp_activity_path, notice: 'Pedido cancelado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :amount, :adress, :status,:cpf)
    end

    def atualiza
      @order.update(order_params)
    end

end

EP3/app/helpers/orders_helper.rb
module OrdersHelper
end

EP3/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Produto%><br>
    <%@products = Product.all%>
    <%= f.select :name, @products.collect {|product| [ product.name]},class: "form-control" %>


  </div>
  <div class="field">
    <%= f.label :Quantidade %><br>
    <%= f.number_field :amount, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :Endereço %><br>
    <%= f.text_field :adress, class: "form-control", :value => current_user.address  %>
  </div><br>

  <%= f.hidden_field(:cpf, :value => current_user.cpf) %>
  <%= f.hidden_field(:status, :value => "Pedido realizado com sucesso!") %>

  <div class="actions">
    <%= f.submit "Confirmar", class: "btn btn-primary" %>
  </div>
<% end %>

EP3/app/views/orders/edit.html.erb
<h1>Editar Pedido</h1>

  <%= render 'form' %>
<%if policy(@order).edit? %>
  <%= link_to 'Mostrar', @order %> |
  <%= link_to 'Voltar', orders_path %>
<%end%>

EP3/app/views/orders/index.html.erb
<h1>Acompanhamento de Pedidos</h1>

<table width="90%" border ="3" >
 <thead>
 <tr lign="center">
    <th>Produto </th>
    <th>Quantidade</th>
    <th>Endereço</th>
    <th>Status </th>
 </tr>
 </thead>

 <tbody>
   <% @orders.each do |order| %>
        <%if (current_user.cpf == order.cpf)%>
        <tr align="center">
            <td><%= order.name %></td>
            <td><%= order.amount %></td>
            <td><%= order.adress %></td>
            <td><%= order.status %></td>

            <%if policy(@orders).index? %>
              <td><%= link_to 'Mostrar Pedido', order %></td>
              <td><%= link_to 'Editar Pedido', edit_order_path(order) %></td>
              <td><%= link_to 'Cancelar Pedido', order, method: :delete, data: { confirm: 'Deseja cancelar o pedido?' } %></td>
            <%end%>
        </tr>
        <%end%>
      <%end%>

  </tbody>
</table>
<br>
<%= button_to 'Novo Pedido', new_order_path, class: "btn btn-primary",:method => :get  %> <br>
<%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>

EP3/app/views/orders/new.html.erb
  <h1>Novo Pedido</h1>

  <%= render 'form' %><br>
  <%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>

EP3/app/views/orders/show.html.erb
<h1>Relatório do pedido</h1>
  <p>
    <strong>Nome:</strong>
    <%= @order.name %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= @order.amount %>
  </p>

  <p>
    <strong>Endereço para entrega:</strong>
    <%= @order.adress %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @order.status %>
  </p>
<br>
  <%= button_to 'Novo Pedido', new_order_path, class: "btn btn-primary",:method => :get  %> <br>
  <%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>