EP3/config/routes.rb
Rails.application.routes.draw do
  get 'controll_user/index'
  get 'controll_user/analise'

  resources :cardapio
  resources :routines
  resources :products
  resources :orders
  root 'main#index'

  get 'account_manager/index'
  get 'account_manager/emp_entry_time'
  get 'account_manager/emp_exit_time'
  get 'account_manager/emp_activity'
  get 'account_manager/atualiza'
    get 'account_manager/caixa'

  Rails.application.routes.draw do
    devise_for :users, :controllers => { :registrations => 'registrations'}
  end

end

EP3/app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", small: "120x120>" }, default_url: ":style/default-no-image.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

EP3/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    authorize @products
  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
  end

  # GET /products/1/edit
  def edit

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Produto cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Produto atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produto deletado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :ingredients,:image)
    end
end

EP3/app/helpers/products_helper.rb
module ProductsHelper
end

EP3/app/views/products/_form.html.erb
<%= form_for @product, html: {multipart: true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_do_produto %><br>
    <%= f.text_field :name,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :preço %><br>
    <%= f.text_field :price,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :ingredientes %><br>
    <%= f.text_area :ingredients,class: "form-control" %>
  </div>
    <br>
  <div class="field">
    <%= f.label :selecionar_uma_imagem %><br>
    <%= f.file_field :image,accept: 'image/png,image/gif,image/jpeg'%>
  </div>


  <br>
  <div class="actions">
    <%= f.submit "Cadastrar produto!", class: "btn btn-primary" %>
  </div>
<% end %>

EP3/app/views/products/edit.html.erb
<h1>Editar Produtos</h1>

<%= render 'form' %>

<%if policy(@product).edit? %>
|
  <%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>
<%end%>

EP3/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listagem de Produtos</h1>

<table class= "product-table" border= 1>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preço</th>
      <th>Ingredientes</th>
      <th>Imagem</th>
      <th>Controle<th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.ingredients %></td>
        <td><%= image_tag product.image.url(:small) %></td>
    <%if policy(@products).index? %>
        <td><%= link_to 'Mostrar informações do produto', product %></td>
        <td><%= link_to 'Editar Produto', edit_product_path(product) %></td>
        <td><%= link_to 'Excluir Produto', product, method: :delete, data: { confirm: 'Deseja excluir o produto?' } %></td>
      </tr>
    <% end %>
  <%end%>
  </tbody>
</table>

<br>

<%= button_to 'Cadastrar Novo Produto', new_product_path, class: "btn btn-primary",:method => :get %><br>
<%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>

EP3/app/views/products/new.html.erb
<h1>Novo Produto</h1>

  <%= render 'form' %>
  <br>
  <%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>

EP3/app/views/products/show.html.erb
<h1>Relatório do produto</h1>
<p>
  <strong>Nome:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Ingredientes:</strong>
  <%= @product.ingredients %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= image_tag @product.image.url(:small) %>
</p>

<%if policy(@product).show? %>
  <%= button_to 'Novo Cadastro', new_product_path, class: "btn btn-primary",:method => :get  %> <br>
  <%= button_to 'Voltar', account_manager_index_path, class: "btn btn-primary",:method => :get  %>
<%end%>